---
- name: Bootstrap personal environment
  hosts: all
  gather_facts: true

  roles:
    - core
    - deploy_user
    - initialize
    - firewall
    - swapfile
    - nginx
    - v2ray
    - certbot
    - umami_nginx

    # Run this manually
    # - ssh_hardening
