---
- name: Bootstrap personal environment
  hosts: all
  gather_facts: true

  roles:
    - role: core
      tags: [core]
    - role: deploy_user
      tags: [deploy_user]
    - role: initialize
      tags: [initialize]
    - role: locales
      tags: [locales]
    - role: firewall
      tags: [firewall]
    - role: swapfile
      tags: [swapfile]
    - role: certbot
      tags: [certbot]
    - role: v2ray
      tags: [v2ray]
    - role: nginx
      tags: [nginx]
    # - role: umami_nginx
    #   tags: [umami_nginx]

    # Run this manually
    # - ssh_hardening
