---
- name: Set up personal dotfiles
  tags: dotfiles
  block:
    - name: Clone the dotfiles repo into the home directory
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          cd "{{ ansible_env.HOME }}"
          git config --global init.defaultBranch main
          git init
          git remote add origin https://github.com/TheClooneyCollection/dotfiles.git
          git fetch origin
          git switch -c main --track origin/main
        creates: "{{ ansible_env.HOME }}/.git"
      register: cloned_dotfile

    - name: Update the dotfiles repo
      ansible.builtin.command:
        cmd: git pull --rebase
        chdir: "{{ ansible_env.HOME }}"
      when: not cloned_dotfile.changed
      register: updated_dotfile
      changed_when: '"Already up to date" not in updated_dotfile.stdout'