---
- name: Install Certbot packages
  become: true
  ansible.builtin.apt:
    name: "{{ certbot_packages }}"
    state: present
    update_cache: true

- name: Request certificates via Certbot (nginx)
  become: true
  ansible.builtin.command:
    cmd: >-
      certbot --nginx --non-interactive --agree-tos
      --email {{ certbot_email }}
      {{ certbot_domains | map('regex_replace', '^(.*)$', '-d \1') | join(' ') }}
  when: certbot_issue_certificates | bool
  register: certbot_issue
  changed_when: certbot_issue.rc == 0

- name: Ensure Certbot timer is enabled
  become: true
  ansible.builtin.systemd:
    name: certbot.timer
    enabled: true
    state: started
    daemon_reload: true

- name: Ensure legacy Certbot cron is absent
  become: true
  ansible.builtin.cron:
    name: Certbot automatic renewal
    state: absent
    user: root
