---
- name: Check for V2Ray binary
  ansible.builtin.stat:
    path: /usr/local/bin/v2ray
  register: v2ray_binary

- name: Download V2Ray install script
  become: true
  ansible.builtin.get_url:
    url: https://install.direct/go.sh
    dest: "{{ v2ray_install_script_path }}"
    mode: '0755'
  when: not v2ray_binary.stat.exists

- name: Run V2Ray install script
  become: true
  ansible.builtin.command:
    cmd: "{{ v2ray_install_script_path }}"
  when: not v2ray_binary.stat.exists
  register: v2ray_install
  changed_when: v2ray_install.rc == 0
  notify: Restart V2Ray

- name: Deploy V2Ray configuration
  become: true
  ansible.builtin.template:
    src: "{{ v2ray_config_template }}"
    dest: "{{ v2ray_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart V2Ray

- name: Ensure V2Ray service is enabled and running
  become: true
  ansible.builtin.service:
    name: "{{ v2ray_service_name }}"
    state: started
    enabled: true
